repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami


helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600


releases:
- name: prod
  namespace: prod
  chart: bitnami/kafka
  set:
  - name: image.tag
    value: 3.5.2
  - name: broker.replicaCount
    value: 5
  - name: listeners.client.protocol
    value: SASL_PLAINTEXT
  - name: listeners.interbroker.protocol
    value: SASL_PLAINTEXT
- name: dev
  namespace: dev
  chart: bitnami/kafka
  set:
  - name: image.tag
    value: latest
  - name: broker.replicaCount
    value: 1
  - name: controller.replicaCount
    value: 1
  - name: listeners.client.protocol
    value: PLAINTEXT
  - name: listeners.interbroker.protocol
    value: PLAINTEXT
