apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: mysql
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-mysql
  namespace: default
roleRef:
  kind: ClusterRole
  name: mysql
  apiGroup: rbac.authorization.k8s.io
