{{- if $.Values.deploy.ingress.enabled -}}

{{- if and $.Values.deploy.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $.Values.deploy.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $.Values.deploy.ingress.annotations "kubernetes.io/ingress.class" $.Values.deploy.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: webserver
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
  {{- with $.Values.deploy.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.deploy.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.deploy.ingress.className }}
  {{- end }}
  {{- if $.Values.deploy.ingress.tls }}
  tls:
    {{- range $.Values.deploy.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $.Values.deploy.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          - pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
              {{- else }}
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
              {{- end }}
            path: {{ .path }}
          {{- end }}
    {{- end }}
{{- end }}
