{{- range $kv := $.Values.deploy.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $kv.name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $kv.saName }}
{{- if $kv.labels}}
  labels:
{{- range $lk, $lv := $kv.labels }}
    {{ $lk }}: {{ $lv | quote }}
{{- end }}  
{{- end }}
type: kubernetes.io/service-account-token
{{- end }}