apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.deploy.service.name }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "homework-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-{{ $.Values.deploy.service.port }}
      port: {{ $.Values.deploy.service.port }}
      targetPort:  {{ $.Values.deploy.service.targetPort }}
      protocol: TCP
  type: {{ .Values.deploy.service.type }}
