{{- if $.Values.deploy.serviceAccount.create }}
{{- range $kv := $.Values.deploy.serviceAccount.items }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $kv.name }}
  namespace: {{ $.Values.global.namespace }}
{{-  if $kv.secrets }}
secrets:
{{- range $s := $kv.secrets }}
- name: {{ $s.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}