kind: Service
apiVersion: v1
metadata:
  name: webserver
  namespace: homework
  labels:
    app.kubernetes.io/instance: webserver
    app.kubernetes.io/name: webserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ports:
  - name: http-8000
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: webserver
  type: ClusterIP
